name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
      - cron: "0 13 * * 1"  # Every Monday at 9AM EST

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install imageruler

      - name: cavity_design
        run: |
          cd cavity_design
          python minimum_lengthscales_run.py
          cd ..

      - name: Metagrating3D
        run: |
          cd Metagrating3D
          python minimum_lengthscales_run.py
          cd ..

      - name: RGB_metalens
        run: |
          cd RGB_Metalens
          python minimum_lengthscales_run.py
          cd ..

      - name: waveguide_mode_converter
        run: |
          cd waveguide_mode_converter
          python run.py designs/converter_generator_circle_6_x47530832_w1_s796.csv 
          cd ..
